package angelesdelcielo.view;

import javax.swing.JInternalFrame;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MainView extends javax.swing.JFrame {

	/**
	 * Creates new form MateView
	 */
	public MainView() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      fileMenu = new javax.swing.JMenu();
      exitMenuItem = new javax.swing.JMenuItem();
      menuMatematicas = new javax.swing.JMenu();
      menuMatematicasFactorial = new javax.swing.JMenuItem();
      menuMatematicasMcdMcm = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("MATEMATICAS");

      fileMenu.setMnemonic('f');
      fileMenu.setText("File");

      exitMenuItem.setMnemonic('x');
      exitMenuItem.setText("Exit");
      exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitMenuItemActionPerformed(evt);
         }
      });
      fileMenu.add(exitMenuItem);

      menuBar.add(fileMenu);

      menuMatematicas.setText("Matemáticas");

      menuMatematicasFactorial.setText("Factorial");
      menuMatematicasFactorial.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuMatematicasFactorialActionPerformed(evt);
         }
      });
      menuMatematicas.add(menuMatematicasFactorial);

      menuMatematicasMcdMcm.setText("MCD y MCM");
      menuMatematicasMcdMcm.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuMatematicasMcdMcmActionPerformed(evt);
         }
      });
      menuMatematicas.add(menuMatematicasMcdMcm);

      menuBar.add(menuMatematicas);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		 System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   private void menuMatematicasFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatematicasFactorialActionPerformed
		mostrarForm(FactorialView.class);
   }//GEN-LAST:event_menuMatematicasFactorialActionPerformed

   private void menuMatematicasMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatematicasMcdMcmActionPerformed
		mostrarForm(McdMcmView.class);
   }//GEN-LAST:event_menuMatematicasMcdMcmActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenuItem exitMenuItem;
   private javax.swing.JMenu fileMenu;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuMatematicas;
   private javax.swing.JMenuItem menuMatematicasFactorial;
   private javax.swing.JMenuItem menuMatematicasMcdMcm;
   // End of variables declaration//GEN-END:variables

	private void mostrarForm(Class<?> aClass) {

		try {

			// Variable de control
			JInternalFrame view = null;

			// Buscar instancia
			for (JInternalFrame form : desktopPane.getAllFrames()) {
				if (aClass.isInstance(form)) {
					view = form;
					break;
				}
			}

			// Crear instancia
			if (view == null) {
				//view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
				view = (JInternalFrame) aClass.getConstructor().newInstance();
				desktopPane.add(view);
				view.setVisible(true);
			}
			view.setSelected(true);

		} catch (Exception e) {
		}

	}

}
