package com.igh.eurekaapp.view;

import com.igh.eurekaapp.controller.ReporteController;
import com.igh.eurekaapp.util.Mensaje;
import java.awt.BorderLayout;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class ReporteListaCuentas extends javax.swing.JInternalFrame {

	private ReporteController reporteController;

	/**
	 * Creates new form ReporteListaCuentas
	 */
	public ReporteListaCuentas() {
		initComponents();
		reporteController = new ReporteController();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      btnSalir = new javax.swing.JButton();
      btnGrabar = new javax.swing.JButton();
      panelReporte = new javax.swing.JPanel();

      setClosable(true);
      setMaximizable(true);
      setTitle("REPORTE DE CUENTAS");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 204))); // NOI18N

      btnSalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      btnSalir.setText("Salir");
      btnSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalirActionPerformed(evt);
         }
      });

      btnGrabar.setBackground(new java.awt.Color(0, 255, 255));
      btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      btnGrabar.setText("Mostrar");
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(240, 240, 240)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(602, Short.MAX_VALUE))
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(27, 27, 27)
               .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(806, Short.MAX_VALUE)))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(8, 8, 8)
               .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(19, Short.MAX_VALUE)))
      );

      panelReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 204))); // NOI18N

      javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
      panelReporte.setLayout(panelReporteLayout);
      panelReporteLayout.setHorizontalGroup(
         panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 1042, Short.MAX_VALUE)
      );
      panelReporteLayout.setVerticalGroup(
         panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 460, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
		this.dispose();
   }//GEN-LAST:event_btnSalirActionPerformed

   private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
		try {

			// Obtener los datos
			List<Map<String, ?>> lista = reporteController.obtenerListaCuentas();
			// Preparar reporte
			JRMapCollectionDataSource data = new JRMapCollectionDataSource(lista);
			Map pars = new HashMap();
			String reporte = "/reportes/ReporteCuentas2.jrxml";
			InputStream is = getClass().getResourceAsStream(reporte);
			if (is == null) {
				throw new RuntimeException("No carga el reporte.");
			}
			JasperReport rep = JasperCompileManager.compileReport(is);
			JasperPrint print = JasperFillManager.fillReport(rep, pars, data);
			// Se crea el visor del reporte
			JRViewer jRViewer = new JRViewer(print);
			// Se elimina elementos del contenedor JPanel
			panelReporte.removeAll();
			// Para el tamaño del reporte se agrega un BorderLayout
			panelReporte.setLayout(new BorderLayout());
			panelReporte.add(jRViewer, BorderLayout.CENTER);
			jRViewer.setVisible(true);
			panelReporte.repaint();
			panelReporte.revalidate();
		} catch (Exception e) {
			//e.printStackTrace();
			Mensaje.error(rootPane, e.getMessage());
		}
   }//GEN-LAST:event_btnGrabarActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnGrabar;
   private javax.swing.JButton btnSalir;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel panelReporte;
   // End of variables declaration//GEN-END:variables

}
