package com.igh.eurekaapp.view;

import com.igh.eurekaapp.dto.EmpleadoDto;
import com.igh.eurekaapp.util.Session;
import javax.swing.JInternalFrame;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class MainFormView extends javax.swing.JFrame {

	/**
	 * Creates new form MainFormView
	 */
	public MainFormView() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setExtendedState(MAXIMIZED_BOTH);
		establecerTitulo();
	}

	private void establecerTitulo() {
		EmpleadoDto bean = (EmpleadoDto) Session.get("USUARIO");
		String titulo = "EUREKA APP (Usuario: " + bean.getNombre().toUpperCase() + ")";
		this.setTitle(titulo);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      fileMenu = new javax.swing.JMenu();
      openMenuItem = new javax.swing.JMenuItem();
      saveMenuItem = new javax.swing.JMenuItem();
      saveAsMenuItem = new javax.swing.JMenuItem();
      exitMenuItem = new javax.swing.JMenuItem();
      editMenu = new javax.swing.JMenu();
      cutMenuItem = new javax.swing.JMenuItem();
      copyMenuItem = new javax.swing.JMenuItem();
      pasteMenuItem = new javax.swing.JMenuItem();
      deleteMenuItem = new javax.swing.JMenuItem();
      helpMenu = new javax.swing.JMenu();
      contentMenuItem = new javax.swing.JMenuItem();
      aboutMenuItem = new javax.swing.JMenuItem();
      menuProcesos = new javax.swing.JMenu();
      menuProcesosCrearCuenta = new javax.swing.JMenuItem();
      menuReportes = new javax.swing.JMenu();
      menuReportesListaCuentas = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      fileMenu.setMnemonic('f');
      fileMenu.setText("File");

      openMenuItem.setMnemonic('o');
      openMenuItem.setText("Open");
      fileMenu.add(openMenuItem);

      saveMenuItem.setMnemonic('s');
      saveMenuItem.setText("Save");
      fileMenu.add(saveMenuItem);

      saveAsMenuItem.setMnemonic('a');
      saveAsMenuItem.setText("Save As ...");
      saveAsMenuItem.setDisplayedMnemonicIndex(5);
      fileMenu.add(saveAsMenuItem);

      exitMenuItem.setMnemonic('x');
      exitMenuItem.setText("Exit");
      exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitMenuItemActionPerformed(evt);
         }
      });
      fileMenu.add(exitMenuItem);

      menuBar.add(fileMenu);

      editMenu.setMnemonic('e');
      editMenu.setText("Edit");

      cutMenuItem.setMnemonic('t');
      cutMenuItem.setText("Cut");
      editMenu.add(cutMenuItem);

      copyMenuItem.setMnemonic('y');
      copyMenuItem.setText("Copy");
      editMenu.add(copyMenuItem);

      pasteMenuItem.setMnemonic('p');
      pasteMenuItem.setText("Paste");
      editMenu.add(pasteMenuItem);

      deleteMenuItem.setMnemonic('d');
      deleteMenuItem.setText("Delete");
      editMenu.add(deleteMenuItem);

      menuBar.add(editMenu);

      helpMenu.setMnemonic('h');
      helpMenu.setText("Help");

      contentMenuItem.setMnemonic('c');
      contentMenuItem.setText("Contents");
      helpMenu.add(contentMenuItem);

      aboutMenuItem.setMnemonic('a');
      aboutMenuItem.setText("About");
      helpMenu.add(aboutMenuItem);

      menuBar.add(helpMenu);

      menuProcesos.setText("Procesos");

      menuProcesosCrearCuenta.setText("Crear cuenta");
      menuProcesosCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosCrearCuentaActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosCrearCuenta);

      menuBar.add(menuProcesos);

      menuReportes.setText("Reportes");

      menuReportesListaCuentas.setText("Listado de cuentas");
      menuReportesListaCuentas.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuReportesListaCuentasActionPerformed(evt);
         }
      });
      menuReportes.add(menuReportesListaCuentas);

      menuBar.add(menuReportes);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		 System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   private void menuProcesosCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosCrearCuentaActionPerformed
		/*
		JInternalFrame view = new ProcesoCrearCuentaView();
		desktopPane.add(view);
		view.setVisible(true);
		*/
		mostrarForm(ProcesoCrearCuentaView.class);
   }//GEN-LAST:event_menuProcesosCrearCuentaActionPerformed

   private void menuReportesListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesListaCuentasActionPerformed
      mostrarForm(ReporteListaCuentas.class);
   }//GEN-LAST:event_menuReportesListaCuentasActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFormView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem aboutMenuItem;
   private javax.swing.JMenuItem contentMenuItem;
   private javax.swing.JMenuItem copyMenuItem;
   private javax.swing.JMenuItem cutMenuItem;
   private javax.swing.JMenuItem deleteMenuItem;
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenu editMenu;
   private javax.swing.JMenuItem exitMenuItem;
   private javax.swing.JMenu fileMenu;
   private javax.swing.JMenu helpMenu;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuProcesos;
   private javax.swing.JMenuItem menuProcesosCrearCuenta;
   private javax.swing.JMenu menuReportes;
   private javax.swing.JMenuItem menuReportesListaCuentas;
   private javax.swing.JMenuItem openMenuItem;
   private javax.swing.JMenuItem pasteMenuItem;
   private javax.swing.JMenuItem saveAsMenuItem;
   private javax.swing.JMenuItem saveMenuItem;
   // End of variables declaration//GEN-END:variables

	private void mostrarForm(Class<?> aClass) {

		try {

			// Variable de control
			JInternalFrame view = null;

			// Buscar instancia
			for (JInternalFrame form : desktopPane.getAllFrames()) {
				if (aClass.isInstance(form)) {
					view = form;
					break;
				}
			}

			// Crear instancia
			if (view == null) {
				//view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
				view = (JInternalFrame) aClass.getConstructor().newInstance();
				desktopPane.add(view);
				view.setVisible(true);
			}
			view.setSelected(true);

		} catch (Exception e) {
		}

	}

}
